//
// Generated file, do not edit! Created by nedtool 5.3 from FOMJob.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FOMJOB_M_H
#define __FOMJOB_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>FOMJob.msg:16</tt> by nedtool.
 * <pre>
 * message FOMJob
 * {
 *     int source;
 *     int destination;
 *     int deadline \@unit(s);
 * }
 * </pre>
 */
class FOMJob : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int deadline;

  private:
    void copy(const FOMJob& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FOMJob&);

  public:
    FOMJob(const char *name=nullptr, short kind=0);
    FOMJob(const FOMJob& other);
    virtual ~FOMJob();
    FOMJob& operator=(const FOMJob& other);
    virtual FOMJob *dup() const override {return new FOMJob(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getDeadline() const;
    virtual void setDeadline(int deadline);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FOMJob& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FOMJob& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FOMJOB_M_H

